import Wrapper from "@/layouts/wrapper";
import type { Metadata } from "next";
import "./global-styling.scss";
import "./globals.css";
import { gilroy, neueRegular, gellery } from "@/lib/fonts"; // Updated import
import { Syne } from "next/font/google";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const syne_body = Syne({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-syne",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${syne_body.variable} ${gellery.variable} ${gilroy.variable} ${neueRegular.variable} antialiased`}
      >
        <Wrapper showBackToTop={false}>{children}</Wrapper>
      </body>
    </html>
  );
}
